anushkaa-dubey/QuickQR

index.html, script.js, style.css
Resolved QR Code Download Issue:
Implemented a dynamic link creation approach to ensure QR code downloads work across all browsers. Added a temporary <a> element with a download attribute, programmatically triggered for reliable file saving. Enhanced QR Code Generation Logic:
Ensured the QR code download button updates with the correct image data after generation. Improved logo handling to overlay logos on the QR code without affecting download functionality. General Improvements:
Added input validation to ensure QR code is generated only for non-empty text/URLs. Streamlined DOM manipulation to ensure clean and maintainable code.
@anushkaa-dubey
=> Resolved QR Code Download Issue: #3 (issue no. 3)

index.html, script.js, style.css
made changes to cater issue #12
=> Made UI more professional 

index.html, style.css
https://github.com/user-attachments/assets/671591a1-efa7-479b-92f4-5cdd247086bc
fixed css added animation and font changed 
fix : #2 
closes: #2
=> CSS changes

index.html, script.js, style.css
**Description:**  
🔧 **Feature Update:**  
I have successfully added a **scroll-to-top button** on the homepage to enhance user navigation and improve the overall user experience.  
📋 **Details:**  
- 🖱️ A sleek and responsive **scroll button** is now available, allowing users to easily return to the top of the page with a single click.  
- 🎨 The button is styled to match the website's aesthetic, ensuring seamless integration with the design.  
- 💻 Fully optimized for both desktop and mobile devices.  
- 🚀 Improves usability for long webpages by saving users from excessive scrolling.  
🎉 **UI Enhancements:**  
- Smooth scrolling animation for a visually appealing experience.  
- Visibility control: The button appears only when users scroll down the page.  
📌 **Purpose:**  
This update …
=> ✨ Added Scroll Button to the Homepage for Improved Navigation 🚀

index.html, script.js, style.css
Changes I made this program :
- Added Firebase configuration
- Implemented Google login/logout
- Added login modal and dropdown menu
- Updated UI for auth states
Future Improvements :
- Managing QR to firestore database
- Managing the private keys in the env file
if you allow for this i will work also on these in future
here are some images of the features i added.....
Thank You
=> Add Google Authentication functionality

index.html, script.js, style.css
Added a Feature : Toggle Switch in the top right corner which have two sets of styles , default (light mode) and .dark-mode for dark mode.
=> #20 issue : Successfully Added [NEW FEATURE] Dark Mode Toggle

index.html
updated Footer with social links including linkedin and instagram
=> Updates footer with social links

style.css
**fixed issue no: #37**
🔧 **Resolved Button Overlapping for a Cleaner UI**  
In this update, I have successfully fixed the issue of the **login button** overlapping with the **day/night toggle button**, ensuring a more organized and visually appealing layout.  
✨ Changes Implemented:  
1️⃣ **Proper Spacing:** Adjusted the positioning of both buttons to eliminate overlap and maintain clear separation.  
2️⃣ **Responsive Alignment:** Ensured the buttons align correctly across all screen sizes and devices.  
3️⃣ **UI Consistency:** Maintained uniform spacing and styling, improving the overall navigation experience.  
4️⃣ **Tested Functionality:** Verified the functionality of both buttons, ensuring they work independently without interference.  
This fix enhances the website's usability and …
=> ✅ Fixing the Overlap Issue Between Login and Day/Night Toggle Buttons 

style.css
**fixed issue no: #39**
🌐 **Polished Social Icons for a Sleeker User Experience**  
In this update, I resolved the issue of the unnecessary underline appearing on social icons and improved their hover effects to make the footer more interactive and visually appealing.  
✨ Changes Made:  
1️⃣ **Removed Underline:** Eliminated the default text underline from the social links, ensuring a cleaner and more professional look.  
2️⃣ **Added Icon-Text Padding:** Created proper spacing between the icons and their associated text for better readability.  
3️⃣ **Interactive Hover Effect:** Enhanced the hover effect with:  
- Color transition for text and icons.  
- A subtle background highlight for a modern touch.  
- Slight upward movement on hover for a dynamic feel.  
4️⃣ **Consistent …
=> 🔧 Fixed Social Icon Underline and Enhanced Hover Effects

index.html, script.js, share.html, share.js, style.css
**Changes I made this program :**
- Added Firestore Database in Firebase to store the QR Data in the database.
- Added the share functionality that will help share the QR via url on whatsapp and twitter and add copy link button also.
- Created one page i.e Share Page for which it will help the people / users to come through the url and see the image and able download and share the qr code.
- tried to improve some responsiveness also.
Here are some screenshot regarding my work..
=> Share Button & QR Data in a Database (Firebase)

Code_Of_Conduct.md
=> Added code_of_conduct.md

index.html, script.js, share.js, style.css
**Issue Number :**  #34 
**Changes I made in the code :**
- Added the prompt after social button to sign in into our platform so that it will help gets the user and also able to save their data permanently and able to see their generated qr codes in the manage qr section.
- Created multiple indexes in the firebase to enable fetching of the data can be quick.
- Created the Manage QR Code Feature in which it helps the authenticated user to see their generated QR code through their option and also check the code by clicking on the type of that QR code.
- Added copy link and delete option to delete the qr code when they have to.
- Enable the automatically changing of the creator name of the generated qr code to that authenticated user name if that user was generating the qr code without …
=> Fetch and Showing the Generated QR Codes for the Authenticated Users

index.html, script.js, share.html, share.js, style.css
**Issue Number :**  #53 
This pull request introduces a new feature that allows users to download QR codes in multiple formats, including PNG, JPG, SVG, and PDF. The feature has been implemented across both the main QR code generation page and the shared QR code page.
**Changes I made in the Program :**
- Added a dropdown menu to both the main page and the shared page, allowing users to select the desired format for downloading the QR code.
- The dropdown includes options for **PNG, JPG, SVG,** and **PDF** formats.
- Users can download the QR code as a PNG image. This is the default format and retains the original QR code's transparency.
- Integrated the **jsPDF** library to allow users to download the QR code as a PDF document. This is particularly useful for document embedding and …
=> Added Multi-Format Export Feature for the QR Codes

index.html, script.js, style.css
I added tag for toggle button so that users understand the purpose of toggle button.
closes #50
=> added tag for toggle button

index.html, script.js, style.css
**Issue Number :** #55 
**As I mentioned in the issue that there 3 bugs found by me in the website but after fixing that particular bugs, I discovered few more and for that fixation I taken some new apporach and fix and redesign some of the elements in the website.**
**Bug Fixes :**
1. Fixed the issue where a login prompt appeared multiple times when generating QR codes.
2. Fixed the theme toggle so it stays the same after refreshing the page.
3. Fixed QR code generation errors that happened after the first error.
4. Fixed a problem with writing data to the Firebase database due to permission issues.
5. Fixed the dropdown menu not closing when you click outside it.
6. Fixed toast notifications getting cut off when scrolling.
7. Fixed the issue where multiple QR codes were saved for the …
=> Fixed the Listed & New Addition Bugs Found in the Project

index.html, script.js, style.css
Changes made to resolve issue #66
=> Scanner Added

instruction.html
**Fixed Issue No: #62**
The **scroll button** is a fantastic UI enhancement added to the **Instructions Page** to ensure users have a seamless navigation experience. Here's a breakdown of its functionality and purpose:  
1. **Purpose:**  
This scroll button is designed to improve usability by allowing users to quickly return to the top of the page, saving time and effort while navigating through long content sections.
2. **Design Details:**  
- The button is styled as a circular element with a vibrant **blue (#007bff)** background to ensure visibility.  
- It includes a **Font Awesome arrow icon (`fa-arrow-up`)**, making its purpose immediately clear to users.  
- A subtle **hover effect** enhances interactivity, scaling the button and changing the color to a darker shade of blue …
=> 🚀 Smooth Scroll to Top Button on the Instructions Page

index.html, style.css
enhanced the login page and added the username and password frontend options along with forget password options to 
preview
=> enhanced the login page

index.html, style.css
@anushkaa-dubey Made changes to the footer to resolve issue #65 
I also added few extra links and possibilities to add a few more pages
=> Enhanced Footer

index.html, style.css
Added sign up page for users who dont have an account.
Linked login and signup pages together.
https://github.com/user-attachments/assets/bf96657f-54d1-457f-99bc-bc9cd7cccefa
=> Signup Page added

index.html, script.js, style.css
**Issue Number :** #19 
- Fixed the mobille responsiveness issue and also added the sidebar for the small devices to remove the clusters in the nav section.
- Also improve the some positioning of the some sections and improved overall.
- Fix the duplication of the nav button when trying to edit as they were present hiddenly.
- Also added some mobile responsiveness styles in the code.
=> Fixed the Mobile Responsiveness and done some Design Improvement

index.html, style.css
**fixed issue no: #74**
**Description:**  
In this update, I have **added a scroll-to-top button** on the **Home Page** to enhance user experience and navigation. This allows users to quickly return to the top of the page with a single click! 🔝  
✔️ **Implemented a scroll button** on the Home Page for smooth navigation.  
✔️ **Ensured responsiveness** so the button works across different screen sizes.  
✔️ **Styled the button** to match the existing UI design.  
✔️ **Added smooth scrolling effect** for a better user experience.  
Previously, users had to **manually scroll back to the top**, which could be inconvenient, especially on long pages. With this enhancement, they can now **easily navigate back to the top** with just one tap! 🎯  
✅ Tested the button across various devices to …
=> ⬆️ Added Scroll Button to Home Page 🚀

style.css
description
-
enhanced the dark mode ui by adjusting the text-color, border-radius and other parts to give it a clean and better user experience. 
preview
-
=> enhanced dark mode ui

index.html, style.css
made the login and sign-up pages follow a consistent theme to enhance visual coherence and improve the overall UI aesthetics.
**issue number :** #77 
***before:***
https://github.com/user-attachments/assets/34550f89-6673-4fa3-82b0-03d2b42b5a5e
***after:***
https://github.com/user-attachments/assets/74e6874a-3140-44b6-ac08-0386e3d1de5c
=> Matching signup login UI

index.html
Added an eye button to check the password users have entered in both login and sign up form.
Issue No. : #92
=> added eye button to toggle password visibility

faq.css, faq.html, index.html, style.css
=> added faq section

batch.css, batch.html, faq.html, index.html, instruction.html, style.css
**Issue Number:** #43 
- Tried to add the new logo & its ui in the website.
- Added Some animation on hovering over the logo
- Applied throughout all the pages.
**Screenshots :**
closes #43
=> Tried to Update the Logo and Stlyes

faq.html, index.html, privacy.css, privacy.html, style.css, terms.css, terms.html
closes #91 
Added nice policy pages for both light and dark theme.
=> Policy pages

index.html, instruction.html
closes #103 
✅ Added back button 
✅ Footer links added
=> instructions pages fixes done
